export type FieldDef = { key: string; label: string; type: "text" | "textarea"; bilingual: boolean; group: string };
export type ImageDef = { key: string; label: string; group: string };
export type PageSchema = { label: string; fields: FieldDef[]; images: ImageDef[] };

export const PAGE_SCHEMAS: Record<string, PageSchema> = {
  home: {
    label: "Home / Beranda",
    fields: [
      { key: "heroBadge", label: "Badge", type: "text", bilingual: true, group: "Hero" },
      { key: "heroTitle", label: "Judul", type: "text", bilingual: true, group: "Hero" },
      { key: "heroEdition", label: "Sub-judul (italic)", type: "text", bilingual: true, group: "Hero" },
      { key: "heroDesc", label: "Deskripsi", type: "textarea", bilingual: true, group: "Hero" },
      { key: "explore", label: "Tombol \"Jelajahi\"", type: "text", bilingual: true, group: "Hero" },
      { key: "about", label: "Tombol \"Tentang Kami\"", type: "text", bilingual: true, group: "Hero" },
      { key: "traditionTitle", label: "Judul", type: "text", bilingual: true, group: "100 Tahun Tradisi" },
      { key: "traditionDesc", label: "Deskripsi", type: "textarea", bilingual: true, group: "100 Tahun Tradisi" },
      { key: "legacyTitle", label: "Judul", type: "text", bilingual: true, group: "Legacy" },
      { key: "legacySubtitle", label: "Sub-judul (italic)", type: "text", bilingual: true, group: "Legacy" },
      { key: "legacyDesc", label: "Deskripsi", type: "textarea", bilingual: true, group: "Legacy" },
      { key: "ctaFind", label: "Tombol CTA", type: "text", bilingual: true, group: "Legacy" },
      { key: "differenceTitle", label: "Judul", type: "text", bilingual: true, group: "Experience the Difference" },
      { key: "differenceDesc", label: "Deskripsi", type: "textarea", bilingual: true, group: "Experience the Difference" },
      { key: "smokingExp", label: "Judul", type: "text", bilingual: true, group: "Ultimate Smoking Experience" },
      { key: "smokingDesc", label: "Deskripsi", type: "textarea", bilingual: true, group: "Ultimate Smoking Experience" },
      { key: "recommended", label: "Judul Section", type: "text", bilingual: true, group: "Rekomendasi Produk" },
    ],
    images: [
      { key: "heroImage", label: "Gambar Background", group: "Hero" },
      { key: "legacyImage", label: "Gambar Background", group: "Legacy" },
      { key: "differenceImage", label: "Gambar", group: "Experience the Difference" },
      { key: "smokingImage", label: "Gambar", group: "Ultimate Smoking Experience" },
    ],
  },
  produk: {
    label: "Halaman Produk (listing)",
    fields: [
      { key: "heroTitle", label: "Judul", type: "text", bilingual: true, group: "Hero" },
      { key: "heroSubtitle", label: "Sub-judul (italic)", type: "text", bilingual: true, group: "Hero" },
      { key: "heroDescription", label: "Deskripsi", type: "textarea", bilingual: true, group: "Hero" },
    ],
    images: [],
  },
  "montenegro-black-gold": {
    label: "Koleksi Montenegro: Black Gold",
    fields: [
      { key: "title", label: "Judul", type: "text", bilingual: true, group: "Hero" },
      { key: "desc", label: "Deskripsi (kutipan)", type: "textarea", bilingual: true, group: "Hero" },
    ],
    images: [
      { key: "leftImage", label: "Gambar Kiri", group: "Hero" },
      { key: "rightImage", label: "Gambar Kanan", group: "Hero" },
    ],
  },
  "montenegro-blue-gold": {
    label: "Koleksi Montenegro: Blue Gold",
    fields: [
      { key: "title", label: "Judul", type: "text", bilingual: true, group: "Hero" },
      { key: "desc", label: "Deskripsi (kutipan)", type: "textarea", bilingual: true, group: "Hero" },
    ],
    images: [{ key: "mainImage", label: "Gambar Utama", group: "Hero" }],
  },
  "montenegro-red-gold": {
    label: "Koleksi Montenegro: Red Gold",
    fields: [
      { key: "title", label: "Judul", type: "text", bilingual: true, group: "Hero" },
      { key: "desc", label: "Deskripsi (kutipan)", type: "textarea", bilingual: true, group: "Hero" },
    ],
    images: [{ key: "mainImage", label: "Gambar Utama", group: "Hero" }],
  },
  "montenegro-white-gold": {
    label: "Koleksi Montenegro: White Gold",
    fields: [
      { key: "title", label: "Judul", type: "text", bilingual: true, group: "Hero" },
      { key: "desc", label: "Deskripsi (kutipan)", type: "textarea", bilingual: true, group: "Hero" },
    ],
    images: [{ key: "mainImage", label: "Gambar Utama", group: "Hero" }],
  },
  "tentang-kami": {
    label: "Tentang Kami",
    fields: [
      { key: "badge", label: "Badge", type: "text", bilingual: true, group: "Hero" },
      { key: "tagline", label: "Tagline", type: "textarea", bilingual: true, group: "Hero" },
      { key: "historyBadge", label: "Badge", type: "text", bilingual: true, group: "Sejarah" },
      { key: "historyTitle", label: "Judul", type: "text", bilingual: true, group: "Sejarah" },
      { key: "historySubtitle", label: "Sub-judul (italic)", type: "text", bilingual: true, group: "Sejarah" },
      { key: "historyDesc1", label: "Paragraf 1", type: "textarea", bilingual: true, group: "Sejarah" },
      { key: "historyDesc2", label: "Paragraf 2", type: "textarea", bilingual: true, group: "Sejarah" },
      { key: "experienceTitle", label: "Judul Sub-section Pengalaman", type: "text", bilingual: true, group: "Sejarah" },
      { key: "experienceDesc", label: "Deskripsi Sub-section Pengalaman", type: "textarea", bilingual: true, group: "Sejarah" },
      { key: "nicaraguaTitle", label: "Judul Sub-section Nicaragua", type: "text", bilingual: true, group: "Sejarah" },
      { key: "nicaraguaDesc", label: "Deskripsi Sub-section Nicaragua", type: "textarea", bilingual: true, group: "Sejarah" },
      { key: "innovationTitle", label: "Judul", type: "text", bilingual: true, group: "Inovasi" },
      { key: "innovationSubtitle", label: "Sub-judul (italic)", type: "text", bilingual: true, group: "Inovasi" },
      { key: "innovationDesc", label: "Deskripsi", type: "textarea", bilingual: true, group: "Inovasi" },
      { key: "quote", label: "Kutipan", type: "textarea", bilingual: true, group: "Filosofi" },
      { key: "heritage", label: "Label Heritage", type: "text", bilingual: true, group: "Filosofi" },
      { key: "qualityTitle", label: "Judul", type: "text", bilingual: true, group: "Kualitas (Penutup)" },
      { key: "qualitySubtitle", label: "Sub-judul", type: "text", bilingual: true, group: "Kualitas (Penutup)" },
      { key: "qualityDesc", label: "Deskripsi", type: "textarea", bilingual: true, group: "Kualitas (Penutup)" },
    ],
    images: [
      { key: "heroImage", label: "Gambar Background", group: "Hero" },
      { key: "portraitImage", label: "Gambar Potret", group: "Sejarah" },
      { key: "innovationImage", label: "Gambar Box", group: "Inovasi" },
    ],
  },
  kontak: {
    label: "Kontak",
    fields: [
      { key: "title", label: "Judul", type: "text", bilingual: true, group: "Hero" },
      { key: "subtitle", label: "Sub-judul (italic)", type: "text", bilingual: true, group: "Hero" },
      { key: "whatsapp", label: "Nomor WhatsApp (format: 62811...)", type: "text", bilingual: false, group: "Info Kontak" },
      { key: "email", label: "Email", type: "text", bilingual: false, group: "Info Kontak" },
      { key: "officeLabel", label: "Label Kantor (teks yang tampil)", type: "text", bilingual: false, group: "Info Kontak" },
      { key: "officeAddress", label: "Alamat Lengkap (untuk link Google Maps)", type: "textarea", bilingual: false, group: "Info Kontak" },
    ],
    images: [{ key: "heroImage", label: "Gambar Sisi Kiri Form", group: "Hero" }],
  },
  privacy: {
    label: "Privacy Policy",
    fields: [
      { key: "intro", label: "Pembuka", type: "textarea", bilingual: true, group: "Konten" },
      { key: "dataCollection", label: "Data yang Dikumpulkan", type: "textarea", bilingual: true, group: "Konten" },
      { key: "dataUse", label: "Penggunaan Data", type: "textarea", bilingual: true, group: "Konten" },
      { key: "dataSharing", label: "Berbagi Data ke Pihak Ketiga", type: "textarea", bilingual: true, group: "Konten" },
      { key: "cookies", label: "Cookies & Tracking", type: "textarea", bilingual: true, group: "Konten" },
      { key: "contact", label: "Kontak Terkait Privasi", type: "textarea", bilingual: true, group: "Konten" },
    ],
    images: [],
  },
  shipping: {
    label: "Shipping Policy",
    fields: [
      { key: "intro", label: "Pembuka", type: "textarea", bilingual: true, group: "Konten" },
      { key: "processingTime", label: "Waktu Proses Pesanan", type: "textarea", bilingual: true, group: "Konten" },
      { key: "shippingArea", label: "Area Pengiriman", type: "textarea", bilingual: true, group: "Konten" },
      { key: "shippingCost", label: "Biaya & Estimasi Pengiriman", type: "textarea", bilingual: true, group: "Konten" },
      { key: "packaging", label: "Pengemasan Produk", type: "textarea", bilingual: true, group: "Konten" },
      { key: "damagedItems", label: "Produk Rusak/Hilang Saat Pengiriman", type: "textarea", bilingual: true, group: "Konten" },
    ],
    images: [],
  },
  terms: {
    label: "Terms of Service",
    fields: [
      { key: "intro", label: "Pembuka", type: "textarea", bilingual: true, group: "Konten" },
      { key: "ageRestriction", label: "Batasan Usia (Produk Tembakau)", type: "textarea", bilingual: true, group: "Konten" },
      { key: "orderTerms", label: "Ketentuan Pemesanan", type: "textarea", bilingual: true, group: "Konten" },
      { key: "pricingTerms", label: "Harga & Pembayaran", type: "textarea", bilingual: true, group: "Konten" },
      { key: "ipTerms", label: "Hak Kekayaan Intelektual", type: "textarea", bilingual: true, group: "Konten" },
      { key: "liabilityTerms", label: "Batasan Tanggung Jawab", type: "textarea", bilingual: true, group: "Konten" },
      { key: "governingLaw", label: "Hukum yang Berlaku", type: "textarea", bilingual: true, group: "Konten" },
    ],
    images: [],
  },
  faq: {
    label: "FAQ",
    fields: [
      { key: "q1", label: "Pertanyaan 1", type: "text", bilingual: true, group: "Pertanyaan 1" },
      { key: "a1", label: "Jawaban 1", type: "textarea", bilingual: true, group: "Pertanyaan 1" },
      { key: "q2", label: "Pertanyaan 2", type: "text", bilingual: true, group: "Pertanyaan 2" },
      { key: "a2", label: "Jawaban 2", type: "textarea", bilingual: true, group: "Pertanyaan 2" },
      { key: "q3", label: "Pertanyaan 3", type: "text", bilingual: true, group: "Pertanyaan 3" },
      { key: "a3", label: "Jawaban 3", type: "textarea", bilingual: true, group: "Pertanyaan 3" },
      { key: "q4", label: "Pertanyaan 4", type: "text", bilingual: true, group: "Pertanyaan 4" },
      { key: "a4", label: "Jawaban 4", type: "textarea", bilingual: true, group: "Pertanyaan 4" },
      { key: "q5", label: "Pertanyaan 5", type: "text", bilingual: true, group: "Pertanyaan 5" },
      { key: "a5", label: "Jawaban 5", type: "textarea", bilingual: true, group: "Pertanyaan 5" },
      { key: "q6", label: "Pertanyaan 6", type: "text", bilingual: true, group: "Pertanyaan 6" },
      { key: "a6", label: "Jawaban 6", type: "textarea", bilingual: true, group: "Pertanyaan 6" },
    ],
    images: [],
  },
};
